FROM mcr.microsoft.com/devcontainers/base:ubuntu-22.04

RUN apt-get update && apt-get install -y python3.10 python3-pip \
    && pip3 install rasa \
    && useradd -ms /bin/bash node

USER node

WORKDIR /mika/rasa
