services:
  frontend:
    build:
      context: ../frontend
      dockerfile: ../.devcontainer/Dockerfile.frontend
    volumes:
      - ..:/mika:cached
    command: make start-container
    ports:
      - "5173:5173"
    depends_on:
      - backend
      - rasa
      - db

  backend:
    build:
      context: ../backend
      dockerfile: ../.devcontainer/Dockerfile.backend
    volumes:
      - ..:/mika:cached
    command: make start-container
    ports:
      - "8080:8080"
    depends_on:
      - db

  rasa:
    build:
      context: ../rasa
      dockerfile: ../.devcontainer/Dockerfile.rasa
    volumes:
      - ..:/mika:cached
    command: make start
    ports:
      - "5005:5005"
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: unless-stopped
    env_file:
      - ../backend/.env
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    ports:
      - "127.0.0.1:3306:3306"

volumes:
  mysql-data:
